config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'
  resources :blogs
  resources :favorites, only: [:create, :destroy]
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :blogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  def index
    @blogs = Blog.order(created_at: :desc)
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      redirect_to @blog, notice: "Blog was successfully created."
    else
      render :new
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: "Blog was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: "Blog was successfully destroyed."
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :description, :user_id)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_blog

  def create
    current_user.favorites.create(blog_id: params[:blog_id])
    
  end

  def destroy
    current_user.favorites.find_by(id: params[:id]).destroy
    
  end

  private

  def set_blog
    @blog = Blog.find(params[:blog_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/blogs/_favorite.html.erb
<% if Favorite.find_by(user_id: current_user.id, blog_id: blog.id) %>
  <%= link_to favorite_path(id: current_user.favorites.find_by(blog_id: blog.id), blog_id: blog.id), method: :delete, class: "favorite-link delete-#{blog.id}", remote: true do %>
  
    <i class="material-icons">star</i>
  <% end %>
<% else %>
  <%= link_to favorites_path(blog_id: blog.id), method: :post, class: "favorite-link post-#{blog.id}", remote: true do %>
    <i class="material-icons">star_border</i>
    <% end %>
<% end %>
<%= blog.favorites.length %>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Writer</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.description %></td>
        <td><%= blog.user.name %></td>
        <td><%= link_to 'Show', blog %></td>
        <td id="favorite-<%= blog.id %>">
          <%= render partial: "favorite", locals: { blog: blog } if blog.user != current_user %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog.description %>
</p>

<p>
  <strong>Writer:</strong>
  <%= @blog.user.name %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/favorites/create.js.erb
$("#favorite-<%= @blog.id %>").html("<%= j(render partial: 'blogs/favorite',  locals: { blog: @blog }) %>");

app/views/favorites/destroy.js.erb
$("#favorite-<%= @blog.id %>").html("<%= j(render partial: 'blogs/favorite',  locals: { blog: @blog }) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAjaxTaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>

  <body>
    <% if !user_signed_in? %>
      <%= link_to 'Sign up', new_user_registration_path  %>
      <%= link_to 'Sign in', new_user_session_path %>
    <% else %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete  %>
    <% end %>
    <%= yield %>
  </body>
</html>